-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZrYkdgXSWDCldFde
mdVcONWeLaFQs6sePoBfZGCC4WegCgYIKoZIzj0DAQehRANCAAQO+P1hbJOw7kps
BaD/A4HZ0JPBa9h78IuWQpaPUeRm817Eef0BaE3zTizEpbEMOcnR7G/Xq4Ei+tYy
lNHpzbrg
-----END PRIVATE KEY-----