-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg+Yipp1BrlMJe8D/K
tDt7bRHIMTtm/WvpHUVJZ18mmtmgCgYIKoZIzj0DAQehRANCAARkhBtkvQPTNQo1
2DYtz5iA0Kfaif9hbQ0ZN7xXpJcG+CE+iOaJYmtsgpAssxCgbLvLMu8TKdcs9th1
FI4+sHDz
-----END PRIVATE KEY-----