-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDhF2DFXNXY1EfS6c
2mwsvR08dUIW6MnaA1zm+AxpwxigCgYIKoZIzj0DAQehRANCAATdVe/hjwnKtYLX
JO10QZf9tJCn6noQX7qpsfxVRiYXoiqkZowWcKiPE/tMZWfwuQ2iksHsIZhF0lLI
IzQ9Oez4
-----END PRIVATE KEY-----