-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUxr4rjV9OKgKs3lL
N+1JpwgwbkfQgXsFDIuF/Absah6gCgYIKoZIzj0DAQehRANCAAQq6VlgzjnZfqXS
QSe3Lnyhb8ZhGgHmLtEoPfDs4owb7OMe5Ll2yrjWKct6lw0Lsc3jxMohSgHr7BKK
NAblHN+X
-----END PRIVATE KEY-----