-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglTQpxuZZQ7654ml2
BixHhXsqqLpNY6E5cwuABnJ54/egCgYIKoZIzj0DAQehRANCAARcPjz+FG9IB72Y
EmDW0fgcVXjvXMAxJxJMlBBorijQqydsRTm/gtAmCKm0X9WEmaUHiG+TQgB3Z1f3
R1MkoMMo
-----END PRIVATE KEY-----