-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQga98yI3bcuVJS/ZQr
GXG+aVDaTx6KduZVicvMxxiRYFigCgYIKoZIzj0DAQehRANCAATF6emlmPzYBp7z
Yw49LATQJEbBSCVjhZobXq/dmmacrvRknv1SIowoyGPTNHqJVoP32TQJ1CWrhm2J
/Oc/Y68Q
-----END PRIVATE KEY-----