-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvy0wGhyn+Npe93Jz
mKW8e6IkjOowdlhhjAetTOttuFKgCgYIKoZIzj0DAQehRANCAASjz3CQR7MnYys8
mlo6rQDaL6KwNo/B0H7HmyqVB+ohIj9dONZvBK6aJdb3ElvL7bpdkgqvpeC1D6lU
VF2nf9Hc
-----END PRIVATE KEY-----