-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjLmA5S1fNTSZAJWg
fvaUEpKg1XsKvlVO9Vrb/miDxOWgCgYIKoZIzj0DAQehRANCAATj7Ffy/IuRC2RN
8GXrXvAWJVUlNbPVPYSw5l7Fmp4OTowm4cLGM9todv8cQIhdTPGO+nUVS056Bdue
7M87FD4u
-----END PRIVATE KEY-----