-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxI/TKc3USdUkeSIq
YdveGiKFPiDwO9K1QggbR03SC4SgCgYIKoZIzj0DAQehRANCAAQZN744APoXfCAj
DD6FYgVRxOAqWkEJPhexuP46iNYJFrL//+vzofu8DoZXzQmGXogqFtG6TxRLn7qo
gxQUrunI
-----END PRIVATE KEY-----