-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBrSx82q+2M/+j5y9
a0d3WaUVHTfJPAxBjAYgR7740uagCgYIKoZIzj0DAQehRANCAASWSkS/Bft720Q8
XPS8TZCxza1ecy0HOHtXPDuOqIxifIbqEw5VDPxEHfBqZGo4YFcwhprrYZhcMmKh
MOvZzbWC
-----END PRIVATE KEY-----