-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKKaz0NxikvaSnC7a
w37QIemZNVFtSdOWa/EBCaURDImgCgYIKoZIzj0DAQehRANCAAQapT0w9Z7HRee7
KlQO5SKWboEVFofrToFfGZaxjbHVy9HWM96BQK8zU2TbqkRkN0HWbs9ldAsXQoZ/
r7ABxxXg
-----END PRIVATE KEY-----