-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggvH7KzKcGUxZWxSs
p/DHweViMLUto1eVKTFztJimVRGgCgYIKoZIzj0DAQehRANCAARJjXaDK5HUbTo8
Q1wPTSaYLAoIDxqGFEPjuBRdGj9bO4cvVydJwxe2ZCRFyRkz5Cv8JrLDCu8W51cX
z0x9ccVA
-----END PRIVATE KEY-----