-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyNjkWuRR1lFdSmAc
PDZtakaPQMXTqjPe0t8RS/wjACOgCgYIKoZIzj0DAQehRANCAASEGGzhrZXs/Nez
IteerPKrK7FeY+AiFfI7+Nzbfar7IDpBvPKeX/v2JmqjCLglpHIi57ud7pKpQXpR
9rZ8lp2S
-----END PRIVATE KEY-----