-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcMEEPy40DhWOVUr2
ZIvW76iRyRWaDcZ/wcVvdtrzVDagCgYIKoZIzj0DAQehRANCAAR1NOHzSCNTWAY2
LEaQjD/LP5Sw4A0BOqOeCto6a0i0MzhkcX7/BcBVjQLX96rtt4Ubi6fRx7LKAWY+
j/Hkg/VG
-----END PRIVATE KEY-----