-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgk1AZv2cJhRODGiew
GWBtKL5MtL2QO4SI9vbPDSZ0kaCgCgYIKoZIzj0DAQehRANCAASlbHJ0+BkIwzHk
WJh4yaqB9wuxpDuiEJ7O0uUbQB7cH8irn3K3zqmPaCVKHSLfEPmqA4jZ6t4iWsHK
Mk/5zONu
-----END PRIVATE KEY-----