# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LabangTv' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LabangTv
  pod 'libksygpulive', :git => 'https://github.com/ksvc/KSYLive_iOS.git', :tag => 'v3.0.5'


end

target 'NotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationServiceExtension

end
